# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "terraform-request"
    key            = "infragenie/ab5c0339-857d-466a-bdc1-dea731dac667/2b22af95-7f50-429e-9b07-6bfe9af68e00/terraform.tfstate"
  }
}
