# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/880896bb-d1d1-4876-955f-2f9d1b5c0398/terraform.tfstate"
  }
}
