# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/bc50e3e0-8716-40db-8b4a-274a390bf010/terraform.tfstate"
  }
}
