# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/6f6d0268-0f43-455a-8845-5cc8302b3942/terraform.tfstate"
  }
}
