# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "terraform-request"
    key            = "infragenie/ab5c0339-857d-466a-bdc1-dea731dac667/47e0ae5a-f25e-4287-ace1-c1bbace8b4a4/terraform.tfstate"
  }
}
