# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/5d454fd1-a950-4dd5-8286-a10ef1223393/terraform.tfstate"
  }
}
