# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/e6b470ea-3dc7-4f27-b0a3-42c1bd6b69f6/terraform.tfstate"
  }
}
