# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/6055372e-f0c4-4681-be37-1168f09fb3ce/terraform.tfstate"
  }
}
