# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/a7d9a056-049a-43e0-82e5-ab8a9f875f19/terraform.tfstate"
  }
}
