# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/6678038a-2143-4770-8a09-594971bd7263/terraform.tfstate"
  }
}
