# Auto-generated by InfraGenie — DO NOT EDIT
terraform {
  backend "azurerm" {
    # Configured at apply-time via -backend-config from Settings → Terraform Storage
    key = "7a8a247e-b9a2-4f57-84ad-584eb9b1273e/5934adde-f7a9-40fa-a403-0663168cdbf0/terraform.tfstate"
  }
}
