# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/6de7fc67-ef05-4440-9363-c623e20dbd9a/terraform.tfstate"
  }
}
