# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/9374a4af-1585-4297-a1ca-6349ec9c4b9e/terraform.tfstate"
  }
}
