# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/fefd8153-78e8-4c0d-9fd0-ec8fb4545477/terraform.tfstate"
  }
}
