# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/92cdb97f-c763-4ad9-85b6-0f81daba8c7b/terraform.tfstate"
  }
}
