# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "terraform-request"
    key            = "infragenie/ab5c0339-857d-466a-bdc1-dea731dac667/e86bbcf7-5b2d-49f9-aff8-1c91381a1d9f/terraform.tfstate"
  }
}
