"""Real Terraform runtime for InfraGenie.

Executes real `terraform init / validate / plan / apply / destroy` against the
user's Azure subscription using their Service Principal, and persists state to
Azure Blob Storage after every operation.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("terraform_runtime")

ROOT = Path(__file__).parent
TERRAFORM_ROOT = ROOT / "terraform"
MODULES_DIR = TERRAFORM_ROOT / "modules"
RUNTIME_DIR = TERRAFORM_ROOT / "runtime"
RUNTIME_DIR.mkdir(parents=True, exist_ok=True)

# Path to the terraform binary (installed globally at /usr/local/bin/terraform)
TERRAFORM_BIN = shutil.which("terraform") or "/usr/local/bin/terraform"


# ---------- Runtime folder + tfvars ----------
def runtime_path(workspace_id: str, deployment_id: str) -> Path:
    p = RUNTIME_DIR / workspace_id / deployment_id
    p.mkdir(parents=True, exist_ok=True)
    return p


def _format_tfvars_value(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        return "[" + ", ".join(_format_tfvars_value(x) for x in v) + "]"
    if isinstance(v, dict):
        inner = ", ".join(f'{k} = {_format_tfvars_value(val)}' for k, val in v.items())
        return "{ " + inner + " }"
    s = str(v).replace('"', '\\"')
    return f'"{s}"'


def render_tfvars(vars_map: Dict[str, Any]) -> str:
    lines: List[str] = []
    for k, v in vars_map.items():
        if v in (None, ""):
            continue
        lines.append(f"{k} = {_format_tfvars_value(v)}")
    return "\n".join(lines) + "\n"


def _providers_tf(subscription_id: str) -> str:
    return f"""# Auto-generated by InfraGenie
provider "azurerm" {{
  features {{}}
  subscription_id = "{subscription_id}"
}}
"""


def _backend_tf(container: str, key_prefix: str, workspace_id: str, deployment_id: str) -> str:
    """We DO NOT hardcode storage credentials into backend.tf; we pass them via CLI -backend-config."""
    return f"""# Auto-generated by InfraGenie
terraform {{
  backend "azurerm" {{
    container_name = "{container}"
    key            = "{key_prefix}/{workspace_id}/{deployment_id}/terraform.tfstate"
  }}
}}
"""


def stage(
    workspace_id: str,
    deployment_id: str,
    module_key: str,
    tfvars: Dict[str, Any],
    subscription_id: str,
    tf_storage: Optional[Dict[str, Any]] = None,
) -> Path:
    """Copy module source into runtime folder and write generated .tf files."""
    src = MODULES_DIR / module_key
    dst = runtime_path(workspace_id, deployment_id)
    if src.exists():
        for f in src.iterdir():
            if f.is_file():
                shutil.copy2(f, dst / f.name)
    (dst / "terraform.tfvars").write_text(render_tfvars(tfvars), encoding="utf-8")
    (dst / "providers.tf").write_text(_providers_tf(subscription_id), encoding="utf-8")
    if tf_storage and tf_storage.get("container"):
        (dst / "backend.tf").write_text(
            _backend_tf(
                container=tf_storage["container"],
                key_prefix=tf_storage.get("key_prefix") or "infragenie",
                workspace_id=workspace_id,
                deployment_id=deployment_id,
            ),
            encoding="utf-8",
        )
    else:
        # Local backend fallback (state lives in the runtime folder)
        p = dst / "backend.tf"
        if p.exists():
            p.unlink()
    return dst


# ---------- Terraform CLI runner ----------
def _sp_env(sp: Dict[str, Any]) -> Dict[str, str]:
    """Build the ARM_* env vars needed by the azurerm provider."""
    env = os.environ.copy()
    env["ARM_CLIENT_ID"] = sp.get("client_id") or ""
    env["ARM_CLIENT_SECRET"] = sp.get("client_secret") or ""
    env["ARM_TENANT_ID"] = sp.get("tenant_id") or ""
    env["ARM_SUBSCRIPTION_ID"] = sp.get("subscription_id") or ""
    env["ARM_USE_CLI"] = "false"
    env["TF_INPUT"] = "0"
    env["TF_IN_AUTOMATION"] = "1"
    return env


async def _run(cmd: List[str], cwd: Path, env: Dict[str, str], timeout: int = 900) -> Tuple[int, str, str]:
    """Run a subprocess async, capture stdout+stderr."""
    logger.info("Running: %s (cwd=%s)", " ".join(cmd), cwd)
    proc = await asyncio.create_subprocess_exec(
        *cmd, cwd=str(cwd), env=env,
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    try:
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    except asyncio.TimeoutError:
        proc.kill()
        return 124, "", f"terraform command timed out after {timeout}s"
    return proc.returncode or 0, (stdout or b"").decode("utf-8", "replace"), (stderr or b"").decode("utf-8", "replace")


async def tf_fmt(cwd: Path) -> Tuple[int, str]:
    code, out, err = await _run([TERRAFORM_BIN, "fmt", "-recursive", "-no-color"], cwd, os.environ.copy(), timeout=30)
    return code, (out + "\n" + err)


async def tf_init(cwd: Path, sp: Dict[str, Any], tf_storage: Optional[Dict[str, Any]]) -> Tuple[int, str]:
    args = [TERRAFORM_BIN, "init", "-no-color", "-upgrade=false"]
    if tf_storage and tf_storage.get("storage_account"):
        args += [
            f'-backend-config=storage_account_name={tf_storage["storage_account"]}',
            f'-backend-config=resource_group_name={tf_storage.get("resource_group", "")}',
            f'-backend-config=container_name={tf_storage["container"]}',
        ]
        if tf_storage.get("access_key"):
            args.append(f'-backend-config=access_key={tf_storage["access_key"]}')
        elif tf_storage.get("sas_token"):
            args.append(f'-backend-config=sas_token={tf_storage["sas_token"]}')
    code, out, err = await _run(args, cwd, _sp_env(sp), timeout=180)
    return code, (out + "\n" + err)


async def tf_validate(cwd: Path, sp: Dict[str, Any]) -> Tuple[int, str]:
    code, out, err = await _run([TERRAFORM_BIN, "validate", "-no-color"], cwd, _sp_env(sp), timeout=60)
    return code, (out + "\n" + err)


async def tf_plan(cwd: Path, sp: Dict[str, Any], destroy: bool = False) -> Tuple[int, str, Optional[Dict[str, Any]]]:
    args = [TERRAFORM_BIN, "plan", "-no-color", "-out=plan.tfplan"]
    if destroy:
        args.append("-destroy")
    code, out, err = await _run(args, cwd, _sp_env(sp), timeout=300)
    log = out + "\n" + err
    plan_json = None
    if code == 0:
        # Convert plan to JSON for the UI
        c2, out2, err2 = await _run(
            [TERRAFORM_BIN, "show", "-json", "-no-color", "plan.tfplan"],
            cwd, _sp_env(sp), timeout=60,
        )
        if c2 == 0 and out2:
            try:
                plan_json = json.loads(out2)
                (cwd / "plan.json").write_text(out2, encoding="utf-8")
            except Exception as e:
                logger.warning("plan json parse failed: %s", e)
    return code, log, plan_json


async def tf_apply(cwd: Path, sp: Dict[str, Any]) -> Tuple[int, str, Dict[str, Any]]:
    code, out, err = await _run(
        [TERRAFORM_BIN, "apply", "-no-color", "-auto-approve", "plan.tfplan"],
        cwd, _sp_env(sp), timeout=1500,
    )
    log = out + "\n" + err
    outputs = {}
    if code == 0:
        c2, out2, _ = await _run(
            [TERRAFORM_BIN, "output", "-json", "-no-color"], cwd, _sp_env(sp), timeout=60,
        )
        if c2 == 0 and out2:
            try:
                raw = json.loads(out2)
                outputs = {k: v.get("value") for k, v in raw.items()}
                (cwd / "outputs.json").write_text(json.dumps(outputs, default=str, indent=2), encoding="utf-8")
            except Exception as e:
                logger.warning("outputs parse failed: %s", e)
    return code, log, outputs


async def tf_destroy(cwd: Path, sp: Dict[str, Any]) -> Tuple[int, str]:
    code, out, err = await _run(
        [TERRAFORM_BIN, "apply", "-no-color", "-auto-approve", "plan.tfplan"],
        cwd, _sp_env(sp), timeout=1500,
    )
    return code, (out + "\n" + err)


# ---------- Plan summarizer (real -> UI-friendly) ----------
def summarize_plan(plan_json: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Convert `terraform show -json` output into the same shape our UI expects."""
    actions_out: List[Dict[str, Any]] = []
    if not plan_json:
        return {"summary": "Plan: 0 to add, 0 to change, 0 to destroy.", "actions": [], "outputs": []}
    changes = plan_json.get("resource_changes") or []
    add = change = destroy = 0
    for rc in changes:
        acts = (rc.get("change") or {}).get("actions") or []
        action = "no-op"
        if "create" in acts and "delete" in acts:
            action = "update"
            change += 1
        elif "create" in acts:
            action = "create"
            add += 1
        elif "delete" in acts:
            action = "destroy"
            destroy += 1
        elif "update" in acts:
            action = "update"
            change += 1
        after = (rc.get("change") or {}).get("after") or {}
        details = []
        for k in ("location", "sku_name", "size", "vm_size", "address_space", "administrator_login"):
            if k in after and after[k] not in (None, "", []):
                v = after[k]
                if isinstance(v, list):
                    v = ",".join(map(str, v))
                details.append(f"{k}={v}")
        actions_out.append({
            "action": action,
            "resource_type": rc.get("type"),
            "resource_name": rc.get("name"),
            "details": details[:4],
        })
    return {
        "summary": f"Plan: {add} to add, {change} to change, {destroy} to destroy.",
        "actions": actions_out,
        "outputs": [{"name": k, "value_preview": ""} for k in (plan_json.get("output_changes") or {})],
    }


# ---------- Azure Blob uploader ----------
def _safe_label(raw: str) -> str:
    """Turn a resource name into a safe blob path segment."""
    if not raw:
        return ""
    s = "".join(c if c.isalnum() or c in "-_." else "_" for c in str(raw))
    return s[:40]  # keep it short


def upload_artifacts_sync(
    tf_storage: Dict[str, Any],
    workspace_id: str,
    deployment_id: str,
    runtime: Path,
    files: List[str],
    label: str = "",
) -> Dict[str, str]:
    """Upload terraform artifacts to the configured Azure Storage container.

    Runs synchronously — call inside asyncio.to_thread.
    """
    from azure.storage.blob import BlobServiceClient

    account = tf_storage["storage_account"]
    key = tf_storage.get("access_key")
    container = tf_storage["container"]
    prefix = tf_storage.get("key_prefix") or "infragenie"

    conn = f"DefaultEndpointsProtocol=https;AccountName={account};AccountKey={key};EndpointSuffix=core.windows.net"
    client = BlobServiceClient.from_connection_string(conn)

    safe = f"{_safe_label(label)}-" if label else ""
    # Use first 8 chars of deployment_id for readability
    short_id = deployment_id[:8] if deployment_id else deployment_id
    urls: Dict[str, str] = {}
    for name in files:
        p = runtime / name
        if not p.exists():
            continue
        blob = f"{prefix}/{workspace_id}/{safe}{short_id}/{name}"
        with p.open("rb") as fp:
            client.get_blob_client(container=container, blob=blob).upload_blob(fp, overwrite=True)
        urls[name] = blob
    return urls


async def upload_artifacts(
    tf_storage: Optional[Dict[str, Any]],
    workspace_id: str,
    deployment_id: str,
    runtime: Path,
    files: List[str],
    label: str = "",
) -> Dict[str, str]:
    if not tf_storage or not tf_storage.get("access_key"):
        return {}
    try:
        # Guard: ensure label is never accidentally None
        safe_label = str(label) if label else ""
        return await asyncio.to_thread(
            upload_artifacts_sync, tf_storage, workspace_id, deployment_id, runtime, files, safe_label,
        )
    except Exception as e:
        logger.exception("Blob upload failed: %s", e)
        return {"error": str(e)[:240]}
