# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/4daead51-9d0f-43dd-89f2-4d5b20f15121/terraform.tfstate"
  }
}
