# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/10cd611e-965f-4c7a-ab3c-0d18790e2dfe/terraform.tfstate"
  }
}
