# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/af81c98e-6703-4b15-a742-b711db63d45f/terraform.tfstate"
  }
}
