# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/db3cc4b2-a6c7-490c-b592-33bbc56e98ff/terraform.tfstate"
  }
}
