# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/5746e483-820f-4fbc-b643-1372dfa081e1/terraform.tfstate"
  }
}
