# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "terraform-request"
    key            = "infragenie/ab5c0339-857d-466a-bdc1-dea731dac667/2392a5ba-1ab6-4064-8b78-c72acc4ec308/terraform.tfstate"
  }
}
