# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "terraform-request"
    key            = "infragenie/ab5c0339-857d-466a-bdc1-dea731dac667/07e22975-45db-433f-bb75-e8bc7ecbf81b/terraform.tfstate"
  }
}
