# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/bcdb8b0d-d5c1-466d-85b2-4dc3f3f551c8/terraform.tfstate"
  }
}
