# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/a9f0c04a-1042-4448-8b53-9f31b1dbbd78/terraform.tfstate"
  }
}
