# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/3579328e-241c-4ac1-90a0-ea91a0f4f1ae/terraform.tfstate"
  }
}
