# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/817cc058-26ba-4baf-b101-baa9d190cc66/terraform.tfstate"
  }
}
