# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "infragenie-resources"
    key            = "infragenie/smoketest/48d2f88e-f113-42c4-9665-9cd92a6c71db/terraform.tfstate"
  }
}
