# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/e8105929-b96e-492f-8ad4-9395ef695b09/terraform.tfstate"
  }
}
