# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "terraform-request"
    key            = "infragenie/ab5c0339-857d-466a-bdc1-dea731dac667/a6235949-c626-4737-ba45-b2dca68f9d24/terraform.tfstate"
  }
}
