# Auto-generated by InfraGenie — DO NOT EDIT
terraform {
  backend "azurerm" {
    # Configured at apply-time via -backend-config from Settings → Terraform Storage
    key = "93931a69-abe1-4a46-9f08-756824f21ba7/a89f9c80-4fde-45d9-b3d4-6886dba0a0e9/terraform.tfstate"
  }
}
