name                = "server1"
resource_group_name = "rg-default"
location            = "eastus"
vm_size             = "Standard_B2s"
admin_username      = "Harsh"
admin_password      = "Gondia@321"
