# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/319c64af-9c6f-4a06-9be4-d411e6c6b5a2/terraform.tfstate"
  }
}
