# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/c07235ef-66c1-45f4-bdf8-3fa9fd90ca60/terraform.tfstate"
  }
}
