# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/dcb8e9c9-cfcc-45da-9b19-21037b45d0d9/terraform.tfstate"
  }
}
