# Auto-generated by InfraGenie — DO NOT EDIT
terraform {
  backend "azurerm" {
    # Configured at apply-time via -backend-config from Settings → Terraform Storage
    key = "93931a69-abe1-4a46-9f08-756824f21ba7/79a35844-9927-4a10-b17c-084815b34fd9/terraform.tfstate"
  }
}
