# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/2557ed33-d02c-4562-8741-3ffff6b0435a/terraform.tfstate"
  }
}
