# Auto-generated by InfraGenie — DO NOT EDIT
terraform {
  backend "azurerm" {
    # Configured at apply-time via -backend-config from Settings → Terraform Storage
    key = "93931a69-abe1-4a46-9f08-756824f21ba7/d584a22b-335a-4f58-9949-a31faee59d0b/terraform.tfstate"
  }
}
