# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/d22ade34-d641-4d72-b11a-36024e068ca4/terraform.tfstate"
  }
}
