# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/4abb0487-3871-4005-ad21-f08fe4577bd8/52a500d8-d69d-4c92-9c4a-06a170fead8c/terraform.tfstate"
  }
}
