# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/6764aeb4-6699-4183-a0f5-38ad87f6c00e/terraform.tfstate"
  }
}
