# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/770ec43a-af9f-4027-b0d7-230168dd24de/terraform.tfstate"
  }
}
