# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/66884a7a-8e82-47b5-b542-d3717266fc92/terraform.tfstate"
  }
}
