# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "terraform-request"
    key            = "infragenie/ab5c0339-857d-466a-bdc1-dea731dac667/1ea7743e-6548-49b6-85af-96b36b9f54a4/terraform.tfstate"
  }
}
