# Auto-generated by InfraGenie
terraform {
  backend "azurerm" {
    container_name = "geniedata"
    key            = "infragenie/bc22a3b5-66a0-442a-ab93-90d6dff42e99/472fdda4-11b7-4f2e-bad9-cd2508584c44/terraform.tfstate"
  }
}
